# Generated by Django 3.2.13 on 2022-05-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Карточки товаров',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('current_price', models.PositiveIntegerField(verbose_name='Новая цена')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('brand', models.CharField(max_length=99, verbose_name='Бренд')),
                ('supplier', models.CharField(max_length=99, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Состояние товара',
                'verbose_name_plural': 'Состояния товаров',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_tracking', models.DateTimeField(verbose_name='Время начала отслеживания')),
                ('end_tracking', models.DateTimeField(verbose_name='Время завершения отслеживания')),
                ('interval', models.PositiveIntegerField(choices=[(1, '1'), (12, '12'), (24, '24')], verbose_name='Интервал отслеживания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_card', to='main.product', unique=True, verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отслеживание товара',
                'verbose_name_plural': 'Отслеживания товаров',
            },
        ),
    ]
